verbosity = 2

[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 1800 # seconds = 30 minutes

# [language.rust]
# filetypes = ["rust"]
# roots = ["Cargo.toml"]
# command = "rust-analyzer"
# # settings_section = "rust-analyzer"
# [language.rust.settings.rust-analyzer]
# checkOnSave.command = "clippy"

# [language.typescript]
# filetypes = ["typescript", "javascript"]
# roots = [".git"]
# command = "deno"
# args = ["lsp"]
# [language.typescript.settings.deno]
# enable = true
# lint = true

[language.typescript]
filetypes = ["typescript", "javascript"]
roots = [".git"]
command = "typescript-language-server"
args = ["--stdio"]

[semantic_tokens]
faces = [
    {face="function", token="function"},
    {face="function", token="method"},
]
